AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with a Security Group

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"  # Allows SSH from anywhere
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"  # Allows SSH from anywhere


  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Specify the instance type
      ImageId: ami-088b41ffb0933423f  # Use a valid AMI ID for your region
      SecurityGroups:
        - Ref: MySecurityGroup
      KeyName: 12pm-pass  # Replace with your key pair name
      AvailabilityZone: us-east-2a  # Replace with your preferred AZ
      Tags:
        - Key: Name
          Value: MyEC2Instance
